# See https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#yarn2-configuration

name: 'Setup .yarnrc.yml'
description: 'Creates the .yarnrc.yml file needed to authenticate with the GitHub npm registry.'
inputs:
  NPM_AUTH_TOKEN:
    description: 'The GitHub token to use for authentication.'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Setup Node.js environment
      uses: actions/setup-node@v5
      with:
        node-version: 24

    - name: Setup .yarnrc.yml
      run: |
        yarn config set npmScopes.<GITHUB_ORG_NAME>.npmRegistryServer "https://npm.pkg.github.com"
        yarn config set npmScopes.<GITHUB_ORG_NAME>.npmAlwaysAuth true
        yarn config set npmScopes.<GITHUB_ORG_NAME>.npmAuthToken $NPM_AUTH_TOKEN
      shell: bash
      env:
        NPM_AUTH_TOKEN: ${{ inputs.NPM_AUTH_TOKEN }}
