export enum ServiceType {
  category = 'category',
  categoryItem = 'categoryItem',
  categoryLevel = 'categoryLevel',
  chain = 'chain',
  chainNodeDef = 'chainNodeDef',
  info = 'info',
  node = 'node',
  nodeDef = 'nodeDef',
  record = 'record',
  survey = 'survey',
  taxon = 'taxon',
  taxonomy = 'taxonomy',
  user = 'user',
  userAuthToken = 'userAuthToken',
}
