import {
  getRoot,
  getNodesArray,
  getNodeByUuid,
  getNodesByUuids,
  getNodesByDefUuid,
  getChild,
  getChildren,
  getParent,
  getParentCodeAttribute,
  getDependentCodeAttributes,
  getAncestor,
  getEntityKeyNodes,
  getEntityKeyValues,
  getNodeSiblings,
  isNodeApplicable,
  visitAncestorsAndSelf,
  getAncestorsAndSelf,
  getDescendant,
  getDescendantsOrSelf,
  isDescendantOf,
  visitDescendantsAndSelf,
  getDependentNodePointers,
  getCategoryItemUuid,
  getValidationChildrenCountKey,
} from './_records/recordGetters'

import { addNode, addNodes } from './_records/recordUpdater'

export const Records = {
  // READ
  getRoot,
  getNodesArray,
  getNodeByUuid,
  getNodesByUuids,
  getNodesByDefUuid,
  getChild,
  getChildren,
  getParent,
  getParentCodeAttribute,
  getDependentCodeAttributes,
  getAncestor,
  getEntityKeyNodes,
  getEntityKeyValues,
  getNodeSiblings,
  isNodeApplicable,
  visitAncestorsAndSelf,
  getAncestorsAndSelf,
  getDescendant,
  getDescendantsOrSelf,
  isDescendantOf,
  visitDescendantsAndSelf,
  getDependentNodePointers,
  getCategoryItemUuid,
  getValidationChildrenCountKey,

  // UPDATE
  addNode,
  addNodes,
}
