import {
  getCycle,
  getRoot,
  getNodes,
  getNodesArray,
  getNodeByInternalId,
  getNodesByInternalIds,
  getNodesByDefUuid,
  getChild,
  getChildren,
  getParent,
  getParentCodeAttribute,
  getAncestorCodePath,
  getDependentCodeAttributes,
  getAncestor,
  getEntityKeyNodes,
  getEntityKeyNodesByDefUuid,
  getEntityKeyValues,
  getEntityKeyValuesByDefUuid,
  getEntitySiblings,
  getAttributeSiblings,
  getNodeIndex,
  isNodeApplicable,
  isNodeEditable,
  isNodeVisible,
  visitAncestorsAndSelf,
  getAncestorsAndSelf,
  getDescendant,
  getDescendantsOrSelf,
  isDescendantOf,
  visitDescendantsAndSelf,
  getDependentNodePointers,
  findEntityByKeyValues,
  findEntityWithSameKeysInAnotherRecord,
  getCategoryItemUuid,
  isNodeEmpty,
  isNodeFilledByUser,
  isEmpty,
  getStep,
  isInAnalysisStep,
} from './_records/recordGetters'
import { addNode, addNodes } from './_records/recordUpdater'
import { getEnumeratingCategoryItems, findDependentEnumeratedEntityDefsNotEmpty } from './_records/recordUtils'
import {
  getEntityCompletionPercent,
  getEntityCompletionStats,
  getEntityOwnCompletionPercent,
  getRecordCompletionPercent,
} from './_records/recordCompletion'
import {
  getDescendantPageNodeDefUuids,
  getEntitySubtreeStatus,
  getMultiplePageEntitiesStatus,
  getNodeDefChildrenInOwnPage,
  getPageNodeDefs,
  getPageValidationStatus,
  getRecordPagesValidationProgress,
  nodeBelongsToOwnPage,
  nodeBelongsToPage,
  pageHasOwnErrors,
} from './_records/recordPagesValidation'
import { deleteNode, deleteNodes } from './recordNodesUpdater/recordNodesDeleter'

export const Records = {
  // READ
  getCycle,
  getRoot,
  getNodes,
  getNodesArray,
  getNodeByInternalId,
  getNodesByInternalIds,
  getNodesByDefUuid,
  getChild,
  getChildren,
  getParent,
  getParentCodeAttribute,
  getAncestorCodePath,
  getDependentCodeAttributes,
  getAncestor,
  getEntityKeyNodes,
  getEntityKeyNodesByDefUuid,
  getEntityKeyValues,
  getEntityKeyValuesByDefUuid,
  getEntitySiblings,
  getAttributeSiblings,
  getNodeIndex,
  isNodeApplicable,
  isNodeEditable,
  isNodeVisible,
  visitAncestorsAndSelf,
  getAncestorsAndSelf,
  getDescendant,
  getDescendantsOrSelf,
  isDescendantOf,
  visitDescendantsAndSelf,
  getDependentNodePointers,
  findEntityByKeyValues,
  findEntityWithSameKeysInAnotherRecord,
  getCategoryItemUuid,
  isNodeEmpty,
  isNodeFilledByUser,
  isEmpty,
  getStep,
  isInAnalysisStep,
  getEntityCompletionPercent,
  getEntityCompletionStats,
  getEntityOwnCompletionPercent,
  getRecordCompletionPercent,
  getNodeDefChildrenInOwnPage,
  getPageNodeDefs,
  getDescendantPageNodeDefUuids,
  nodeBelongsToPage,
  nodeBelongsToOwnPage,
  getPageValidationStatus,
  pageHasOwnErrors,
  getRecordPagesValidationProgress,
  getEntitySubtreeStatus,
  getMultiplePageEntitiesStatus,
  // UPDATE
  addNode,
  addNodes,
  deleteNode,
  deleteNodes,
  // Utils
  getEnumeratingCategoryItems,
  findDependentEnumeratedEntityDefsNotEmpty,
}

export type { RecordUpdateOptions } from './_records/recordUpdateOptions'
export type {
  EntitySubtreeStatus,
  PageValidationStatus,
  PagesValidationProgress,
} from './_records/recordPagesValidation'
