import {
  getRoot,
  getNodesArray,
  getChild,
  getChildren,
  getParent,
  getParentCodeAttribute,
  getAncestor,
  getNodeByUuid,
  getEntityKeyNodes,
  getEntityKeyValues,
  getNodeSiblings,
  isNodeApplicable,
  visitAncestorsAndSelf,
  getAncestorsAndSelf,
  getDescendant,
  getDescendantsOrSelf,
  isDescendantOf,
  visitDescendantsAndSelf,
  getDependentNodePointers,
  getCategoryItemUuid,
  getValidationChildrenCountKey,
} from './recordGetters'

import { addNode, addNodes, removeNode, removeNodes } from './recordUpdater'

export const Records = {
  // READ
  getRoot,
  getNodesArray,
  getChild,
  getChildren,
  getParent,
  getParentCodeAttribute,
  getAncestor,
  getNodeByUuid,
  getEntityKeyNodes,
  getEntityKeyValues,
  getNodeSiblings,
  isNodeApplicable,
  visitAncestorsAndSelf,
  getAncestorsAndSelf,
  getDescendant,
  getDescendantsOrSelf,
  isDescendantOf,
  visitDescendantsAndSelf,
  getDependentNodePointers,
  getCategoryItemUuid,
  getValidationChildrenCountKey,

  // UPDATE
  addNode,
  addNodes,
  removeNode,
  removeNodes,
}
