import {
  getRoot,
  getNodesArray,
  getChild,
  getChildren,
  getParent,
  getParentCodeAttribute,
  getAncestor,
  getNodeByUuid,
  getEntityKeyNodes,
  getEntityKeyValues,
  getNodeSiblings,
  isNodeApplicable,
  visitAncestorsAndSelf,
  getAncestorsAndSelf,
  getDescendant,
  getDescendantsOrSelf,
  isDescendantOf,
  visitDescendantsAndSelf,
  getDependentNodePointers,
  getCategoryItemUuid,
  getValidationChildrenCountKey,
} from './recordGetters'

export const Records = {
  getRoot,
  getNodesArray,
  getChild,
  getChildren,
  getParent,
  getParentCodeAttribute,
  getAncestor,
  getNodeByUuid,
  getEntityKeyNodes,
  getEntityKeyValues,
  getNodeSiblings,
  isNodeApplicable,
  visitAncestorsAndSelf,
  getAncestorsAndSelf,
  getDescendant,
  getDescendantsOrSelf,
  isDescendantOf,
  visitDescendantsAndSelf,
  getDependentNodePointers,
  getCategoryItemUuid,
  getValidationChildrenCountKey,
}
