import {
  buildAndAssocDependencyGraph,
  addNodeDefDependencies,
  getNodeDefDependents,
  removeNodeDefDependencies,
} from './dependencies'

import {
  findNodeDefByName,
  findNodeDefByUuid,
  findNodeDefsByUuids,
  getNodeDefByName,
  getNodeDefsByUuids,
  getNodeDefByUuid,
  getNodeDefChildren,
  getNodeDefChildrenSorted,
  getNodeDefParent,
  getNodeDefRoot,
  getNodeDefSource,
  isNodeDefAncestor,
  getNodeDefKeys,
  getRootKeys,
  getNodeDefsIncludedInMultipleEntitySummary,
  getNodeDefParentCode,
  getNodeDefAncestorCodes,
  isNodeDefParentCode,
  getNodeDefCategoryLevelIndex,
  isNodeDefEnumerator,
  getNodeDefEnumerator,
  buildAndAssocNodeDefsIndex,
  addNodeDefToIndex,
  updateNodeDefUuidByNameIndex,
  deleteNodeDefIndex,
  visitAncestorsAndSelfNodeDef,
  visitDescendantsAndSelfNodeDef,
  visitNodeDefs,
  getDescendantsInSingleEntities,
} from './nodeDefs'
import {
  getCategoryItemByCodePaths,
  getCategoryItemByUuid,
  getCategoryItemUuidByCode,
  getCategoryItems,
  getTaxonByCode,
  getTaxonByUuid,
  getTaxonVernacularNameUuid,
  includesTaxonVernacularName,
} from './refsData'

import {
  getName,
  getLanguages,
  getDefaultLanguage,
  getLabel,
  getLabelOrName,
  getDescription,
  getFieldManualLink,
  getCycleKeys,
  getLastCycleKey,
  getDefaultCycleKey,
  getSRSs,
  getSRSByCode,
  getSRSIndex,
  getCategoryByName,
  getCategoryByUuid,
  getTaxonomyByName,
  getTaxonomyByUuid,
} from './surveysGetters'

import {
  getSecurity,
  isDataEditorViewNotOwnedRecordsAllowed,
  isVisibleInMobile,
  isRecordsDownloadInMobileAllowed,
  isRecordsUploadFromMobileAllowed,
} from './surveyGettersSecurity'

export const Surveys = {
  getName,
  getLanguages,
  getDefaultLanguage,
  getLabel,
  getLabelOrName,
  getDescription,
  getFieldManualLink,
  getCycleKeys,
  getLastCycleKey,
  getDefaultCycleKey,
  getSRSs,
  getSRSByCode,
  getSRSIndex,
  getCategoryByName,
  getCategoryByUuid,
  getTaxonomyByName,
  getTaxonomyByUuid,

  findNodeDefByName,
  findNodeDefByUuid,
  findNodeDefsByUuids,
  getNodeDefByName,
  getNodeDefsByUuids,
  getNodeDefByUuid,
  getNodeDefChildren,
  getNodeDefChildrenSorted,
  getNodeDefParent,
  getNodeDefRoot,
  getNodeDefSource,
  isNodeDefAncestor,
  getNodeDefKeys,
  getRootKeys,
  getNodeDefsIncludedInMultipleEntitySummary,
  isNodeDefEnumerator,
  getNodeDefEnumerator,
  visitAncestorsAndSelfNodeDef,
  visitDescendantsAndSelfNodeDef,
  visitNodeDefs,
  getDescendantsInSingleEntities,

  // ref data
  getCategoryItemByCodePaths,
  getCategoryItemByUuid,
  getCategoryItemUuidByCode,
  getCategoryItems,
  getTaxonByCode,
  getTaxonByUuid,
  getTaxonVernacularNameUuid,
  includesTaxonVernacularName,

  // node def code
  getNodeDefParentCode,
  getNodeDefAncestorCodes,
  isNodeDefParentCode,
  getNodeDefCategoryLevelIndex,

  // dependencies
  buildAndAssocDependencyGraph,
  addNodeDefDependencies,
  getNodeDefDependents,
  removeNodeDefDependencies,

  // index
  buildAndAssocNodeDefsIndex,
  addNodeDefToIndex,
  updateNodeDefUuidByNameIndex,
  deleteNodeDefIndex,

  // security
  getSecurity,
  isDataEditorViewNotOwnedRecordsAllowed,
  isVisibleInMobile,
  isRecordsDownloadInMobileAllowed,
  isRecordsUploadFromMobileAllowed,
}
