import {
  addNodeDefDependencies,
  buildAndAssocDependencyGraph,
  getNodeDefDependents,
  getOnUpdateDependents,
  removeNodeDefDependencies,
} from './dependencies'

import {
  addNodeDefToIndex,
  buildAndAssocNodeDefsIndex,
  deleteNodeDefIndex,
  findNodeDefByName,
  findNodeDefByUuid,
  findNodeDefsByUuids,
  getDependentCodeAttributeDefs,
  getDependentEnumeratedEntityDefs,
  getDescendantsInSingleEntities,
  getNodeDefAncestorCodes,
  getNodeDefAncestorMultipleEntity,
  getNodeDefByName,
  getNodeDefByUuid,
  getNodeDefCategoryLevelIndex,
  getNodeDefChildren,
  getNodeDefChildrenSorted,
  getNodeDefEnumerator,
  getNodeDefKeys,
  getNodeDefParent,
  getNodeDefParentCode,
  getNodeDefRoot,
  getNodeDefSource,
  getNodeDefsByUuids,
  getNodeDefsIncludedInMultipleEntitySummary,
  getRootKeys,
  isNodeDefAncestor,
  isNodeDefEnumerator,
  isNodeDefParentCode,
  updateNodeDefUuidByNameIndex,
  visitAncestorsAndSelfNodeDef,
  visitDescendantsAndSelfNodeDef,
  visitNodeDefs,
} from './nodeDefs'
import {
  getCategoryItemByCodePaths,
  getCategoryItemByUuid,
  getCategoryItemUuidByCode,
  getCategoryItems,
  getCategoryItemsByNodeDef,
  getTaxonByCode,
  getTaxonByUuid,
  getTaxonVernacularNameUuid,
  includesTaxonVernacularName,
} from './refsData'

import {
  getCategoryByName,
  getCategoryByUuid,
  getCycleKeys,
  getDefaultCycleKey,
  getDefaultLanguage,
  getDescription,
  getFieldManualLink,
  getLabel,
  getLabelOrName,
  getLanguages,
  getLastCycleKey,
  getName,
  getSRSByCode,
  getSRSIndex,
  getSRSs,
  getTaxonomyByName,
  getTaxonomyByUuid,
} from './surveysGetters'

import {
  getSecurity,
  isDataEditorViewNotOwnedRecordsAllowed,
  isRecordsDownloadInMobileAllowed,
  isRecordsUploadFromMobileAllowed,
  isRecordsWithErrorsUploadFromMobileAllowed,
  isVisibleInMobile,
} from './surveyGettersSecurity'

import { findApplicableDependentEnumeratedEntityDefs, getEnumeratingCategoryItems } from './surveysUtils'

export const Surveys = {
  getName,
  getLanguages,
  getDefaultLanguage,
  getLabel,
  getLabelOrName,
  getDescription,
  getFieldManualLink,
  getCycleKeys,
  getLastCycleKey,
  getDefaultCycleKey,
  getSRSs,
  getSRSByCode,
  getSRSIndex,
  getCategoryByName,
  getCategoryByUuid,
  getTaxonomyByName,
  getTaxonomyByUuid,

  findNodeDefByName,
  findNodeDefByUuid,
  findNodeDefsByUuids,
  getNodeDefByName,
  getNodeDefsByUuids,
  getNodeDefByUuid,
  getNodeDefChildren,
  getNodeDefChildrenSorted,
  getNodeDefParent,
  getNodeDefAncestorMultipleEntity,
  getNodeDefRoot,
  getNodeDefSource,
  isNodeDefAncestor,
  getNodeDefKeys,
  getRootKeys,
  getNodeDefsIncludedInMultipleEntitySummary,
  isNodeDefEnumerator,
  getNodeDefEnumerator,
  visitAncestorsAndSelfNodeDef,
  visitDescendantsAndSelfNodeDef,
  visitNodeDefs,
  getDescendantsInSingleEntities,

  // ref data
  getCategoryItemByCodePaths,
  getCategoryItemByUuid,
  getCategoryItemUuidByCode,
  getCategoryItems,
  getCategoryItemsByNodeDef,
  getTaxonByCode,
  getTaxonByUuid,
  getTaxonVernacularNameUuid,
  includesTaxonVernacularName,

  // node def code
  getNodeDefParentCode,
  getNodeDefAncestorCodes,
  isNodeDefParentCode,
  getNodeDefCategoryLevelIndex,
  getDependentCodeAttributeDefs,
  getDependentEnumeratedEntityDefs,

  // dependencies
  buildAndAssocDependencyGraph,
  addNodeDefDependencies,
  getNodeDefDependents,
  getOnUpdateDependents,
  removeNodeDefDependencies,

  // index
  buildAndAssocNodeDefsIndex,
  addNodeDefToIndex,
  updateNodeDefUuidByNameIndex,
  deleteNodeDefIndex,

  // security
  getSecurity,
  isDataEditorViewNotOwnedRecordsAllowed,
  isVisibleInMobile,
  isRecordsDownloadInMobileAllowed,
  isRecordsUploadFromMobileAllowed,
  isRecordsWithErrorsUploadFromMobileAllowed,

  // utils
  getEnumeratingCategoryItems,
  findApplicableDependentEnumeratedEntityDefs,
}
